services:
    lib.entity_parser:
        class: WH\LibBundle\Services\EntityParser
    lib.useful_functions:
        class: WH\LibBundle\Services\UsefulFunctions
    lib.form_validator:
        class: WH\LibBundle\Services\FormValidator