services:
    lib.entity_parser:
        class: WH\LibBundle\Services\EntityParser
    lib.useful_functions:
        class: WH\LibBundle\Services\UsefulFunctions
    lib.csv_importer:
        class: WH\LibBundle\Services\CsvImporter
        arguments: ['@service_container']
    lib.twig.slug:
        class: WH\LibBundle\Twig\SlugExtension
        arguments: ["@service_container"]
        tags:
            - {name: twig.extension}
    lib.form_error_collector:
        class: WH\LibBundle\Services\FormErrorCollector

    wh.searchfilter:
        class : 'WH\CmsBundle\Filter\SearchFilter'
        arguments: [ '@doctrine', '@request_stack', '@?logger' ]
        tags: [ 'api_platform.filter' ]
